#!/usr/bin/env python3
"""
====================================================================
Package: labware
====================================================================
Author:			Ragdata
Date:			26/02/2026
License:		MIT License
Repository:		https://github.com/Ragdata/labware
Copyright:		Copyright © 2026 Redeyed Technologies
====================================================================
"""
import subprocess, sys


def update(check=True):
	try:
		result = subprocess.run("sudo apt update && sudo apt full-upgrade -y", shell=True, check=check, text=True, capture_output=False, input=None)
		subprocess.run("sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl wget git libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev")
		subprocess.run("sudo apt autoremove -y && sudo apt clean")
		return result
	except subprocess.CalledProcessError as e:
		print(e.output)
		if check:
			sys.exit(1)
